version: '3'
services:
 migration:
   build: .
   environment:
     - DB_HOST=${DB_HOST}
     - DB_PORT=${DB_PORT}
     - DB_NAME=${DB_NAME}
     - DB_USERNAME=${DB_USERNAME}
     - DB_PASSWORD=${DB_PASSWORD}
     - FLASK_ENV=${FLASK_ENV}
     - APP_VERSION=${APP_VERSION}
   command: flask db upgrade
 api:
   build: .
   ports:
    - "5000:5000"
   environment:
     - DB_HOST=${DB_HOST}
     - DB_PORT=${DB_PORT}
     - DB_NAME=${DB_NAME}
     - DB_USERNAME=${DB_USERNAME}
     - DB_PASSWORD=${DB_PASSWORD}
     - FLASK_ENV=${FLASK_ENV}
     - APP_VERSION=${APP_VERSION}
   restart: always  
   depends_on:
     - migration
