apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.secretName }}
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  db_host: {{ .Values.app.dbHost }}
  db_username: {{ .Values.app.dbUsername }}
  db_password: {{ .Values.app.dbPassword }}
