apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.serviceName }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.label }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app.label }}
  ports:
    - port: 80
      name: http
      targetPort: {{ .Values.app.port }}




